# Basic set up for three package managers

version: 2
updates:
  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    target-branch: next
    open-pull-requests-limit: 10
    reviewers:
      - cruex-de
    assignees:
      - cruex-de
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - '📦 dependency'

  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    target-branch: next
    open-pull-requests-limit: 10
    reviewers:
      - cruex-de
    assignees:
      - cruex-de
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - '📦 dependency'

  # Fetch and update the latest dependencies for Docker
  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: weekly
      time: '00:00'
    target-branch: next
    open-pull-requests-limit: 10
    reviewers:
      - cruex-de
    assignees:
      - cruex-de
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - '📦 dependency'
